### ISSUE TITLE
Why GRIP and GRIP++ is not included?

### ISSUE THREAD

**Issue by sourcecode369** [aras62/vision-based-prediction#1]
https://paperswithcode.com/paper/grip-graph-based-interaction-aware-trajectory
https://github.com/xincoder/GRIP

**Comment by aras62** [comment]
Hi,

Thank you for bringing this up to my attention. As mentioned on the home page, due to the volume of the work in this field, I am specifically covering works published in the main CV, Robotics, and ML communities. I have covered some of the earlier works from ITS conferences due to the lower number of papers, however, at this stage recent papers published in ITS 
 conferences or arxiv will not be included.

**Comment by sourcecode369** [comment]
Thanks for answering.
